# Generated by Django 4.2.2 on 2023-09-25 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Default Location', max_length=150),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Default Title', max_length=150),
        ),
    ]
