# Generated by Django 4.2.2 on 2023-10-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHub', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
